### ISSUE TITLE
Selecting entire file causes ArrayOutOfBounds exception to be thrown.

### ISSUE THREAD

**Issue by mikerogne** [RobinMalfait/KopyPasta#2]
Select whole file.
Run KopyPasta.
Exception thrown.

http://screencast.com/t/DzZOCVJIpfz
http://kopy.io/2jo5O

**Comment by Naatan** [comment]
Mind you a kopy by default only lasts for a day, if you want it to last longer you have to change the "Keep For" dropdown. The one you linked to has expired.

**Comment by mikerogne** [comment]
Ah, didn't know that. I think he can still figure out what the issue is :)
